# -*- coding: utf-8 -*-
"""DAA-PRAC(05)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19jhReuiU8ABXf-fJKckWsnyiPKei2IkC
"""

def knapsack(weights, values, capacity):
    n = len(weights)

    # Create DP table
    dp = [[0 for _ in range(capacity + 1)] for _ in range(n + 1)]

    # Fill the DP table
    for i in range(1, n + 1):
        for w in range(1, capacity + 1):

            if weights[i - 1] <= w:
                dp[i][w] = max(
                    values[i - 1] + dp[i - 1][w - weights[i - 1]],
                    dp[i - 1][w]
                )
            else:
                dp[i][w] = dp[i - 1][w]

    return dp[n][capacity]


# User input
n = int(input("Enter number of items: "))

weights = []
values = []

print("Enter weights:")
for i in range(n):
    weights.append(int(input(f"Weight of item {i + 1}: ")))

print("Enter values:")
for i in range(n):
    values.append(int(input(f"Value of item {i + 1}: ")))

capacity = int(input("Enter knapsack capacity: "))

# Calculate maximum value
result = knapsack(weights, values, capacity)

print("Maximum value =", result)