# -*- coding: utf-8 -*-
"""DAA PRAC(4)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13PiQIcOPw6C5PBxed_H8uJGf6Vd6f9HX
"""

#Iterative Method
n = int(input("Enter a number: "))

fact = 1

for i in range(1, n + 1):
    fact = fact * i

print("Factorial =", fact)

#Recursive Method
def factorial(n):
    if n == 0 or n == 1:
        return 1
    return n * factorial(n - 1)

n = int(input("Enter a number: "))

result = factorial(n)

print("Factorial =", result)