# -*- coding: utf-8 -*-
"""DAA 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13PiQIcOPw6C5PBxed_H8uJGf6Vd6f9HX
"""

#  MAX-Heap Sort
import time
import heapq

# User Input
n = int(input("Enter the number of elements: "))
arr = []

print("Enter the elements:")
for i in range(n):
    arr.append(int(input(f"Element {i+1}: ")))

# Measure Execution Time
start = time.perf_counter()

# Convert elements to negative for Max Heap
max_heap = [-x for x in arr]
heapq.heapify(max_heap)

sorted_arr = []
while max_heap:
    sorted_arr.append(-heapq.heappop(max_heap))

end = time.perf_counter()

# Display Result
print("\nSorted Array (Descending Order):")
print(sorted_arr)

print("Execution Time:", end - start, "seconds")

# Time Complexity
print("\nTime Complexity:")
print("Best Case    : O(n log n)")
print("Average Case : O(n log n)")
print("Worst Case   : O(n log n)")

# MIN-Heap Sort
import time
import heapq

# User Input
n = int(input("Enter the number of elements: "))
arr = []

print("Enter the elements:")
for i in range(n):
    arr.append(int(input(f"Element {i+1}: ")))

# Measure Execution Time
start = time.perf_counter()

heapq.heapify(arr)  # Convert list into Min Heap

sorted_arr = []
while arr:
    sorted_arr.append(heapq.heappop(arr))

end = time.perf_counter()

# Display Result
print("\nSorted Array (Ascending Order):")
print(sorted_arr)

print("Execution Time:", end - start, "seconds")

# Time Complexity
print("\nTime Complexity:")
print("Best Case    : O(n log n)")
print("Average Case : O(n log n)")
print("Worst Case   : O(n log n)")